# Generated by Django 4.1.3 on 2023-05-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_address', models.CharField(blank=True, max_length=256, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('status', models.CharField(max_length=100)),
                ('block_number', models.PositiveIntegerField()),
                ('nonce', models.PositiveIntegerField()),
                ('blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
                ('coin_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.coininfo')),
            ],
        ),
    ]
